### ISSUE TITLE
(s || "").replace is not a function

### ISSUE THREAD

**Issue by philwc** [bruceadams/get-release#1]
Hello,

I'm trying to use this action, however, I'm getting the error:

```
(s || "").replace is not a function
```

Are you able to help?

**Comment by bruceadams** [comment]
I have not managed to get this action to work myself. Sorry about that! I have not figured out to effectively test, lint or debug Github actions. It's been a few weeks since I even looked at this. I've been hoping I might find better information from Github or the wider community by waiting a little while. I'll take another look at this in a few hours. (I'm attempting, and largely failing, to focus on my day job right now!)

**Comment by philwc** [comment]
I've found the issue, PR here: https://github.com/bruceadams/get-release/pull/2

It looks like the `escapeData` method deep in the @actions/core library didn't like non-strings...

**Comment by bruceadams** [comment]
What is amazing is: your fix works on macOS. There is similar, still says `(s || "").replace is not a function`, but different failure on Linux and Windows. The visible difference is that there is no stack trace associated with the Linux and Windows failures. Putting a bunch of `console.log` statements, my code appears to never even get loaded.

My wild guess at this point is that something declarative about my action is not quite right. And something on the Github side of the world behaves differently on macOS avoiding the crash.

**Comment by bruceadams** [comment]
Oh, my. I'm just not seeing what's in front of my face. I forgot to update my build's reference to `get-release` in all three places I use it! Working! Yay! Thanks again!
